development:
  adapter: mysql2
  database: Shopulse
  pool: 5
  timeout: 5000
  username: root

production:
  adapter: mysql2
  database: Shopulse
  pool: 5
  timeout: 5000
  username: root

test:
  adapter: mysql2
  database: ShopulseTest
  pool: 5
  timeout: 5000
  username: root