development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ggmichaelgogame@gmail.com
  :password: goodfortune!
  :enable_starttls_auto: true
  
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ggmichaelgogame@gmail.com
  :password: goodfortune!
  :enable_starttls_auto: true